// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhfbbjdoqheppactnphq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoZmJiamRvcWhlcHBhY3RucGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MDQwMTYsImV4cCI6MjA1MDk4MDAxNn0.3OIKD7A6zKxlZsRhIAS9oFYT6tPOChMQ6XSNN7kGWiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);